config/routes.rb
Rails.application.routes.draw do
  
    
    devise_for :admins
 
    devise_scope :admin do
      authenticated :admin do
        root 'admins#index', as: :authenticated_root
    
        get 'admin/index'
            resources :admins
            
        get 'products/create_products' #if not working ~> change to admings
           resources :products
           
        get 'cashiers/create'
          resources :cashiers
        
        end
      end
     
    
    unauthenticated do 
	    root 'devise/sessions#new', as: :unauthenticated_root
	
    end
      
  
 devise_for :cashiers
  #devise_scope: :cashier do #trial
    #authenticated :cashier do
      #root 'cashiers'
    #end
    #end
end
  #get 'cashiers/create'
      #resources :cashiers

  #get 'admins/index'
      #resources :admins
      
 # get 'products/create_products'
  #    resources :products
   

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable :registerable,   and :omniauthable
  devise :database_authenticatable, :recoverable, :registerable,
          :rememberable, :trackable, :validatable
         
  has_many :products
  has_many :cashiers
  
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cashier.rb
class Cashier < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  #belongs_to :admin, optional: true
  
  
  #def to_s
   # "#{:cashier_name}"
  #end
  
  
end

app/models/product.rb
class Product < ApplicationRecord
    #belongs_to :admin
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  
  def index
    @products = Product.all
  end
  
  def show_products
    
  end
  
  
  def show_cashiers
    
  end
  
  def destroy
    
  end
  
  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cashiers_controller.rb
class CashiersController < ApplicationController
  before_action :set_cashier, only: [:show, :edit, :update]
  
  def index
    @cashiers = Cashier.all
  end
  
  def new
    @cashier = Cashier.new
  end
  
  def create
    @cashier = Cashier.new(name: cashier_params["name"], status: cashier_params["status"], admin_id: current_admin.id, password: "password", email: cashier_params["email"])
    # raise @cashier.inspect
    if @cashier.save
      redirect_to @cashier
    end
  end
  
  def show
    
  end
  
  def edit
  end
  
  def update
    if @cashier.update(cashier_params)
      redirect_to @cashier
    end
  end
  
  def destroy
 # @cashier.status=false   
  # @cashier = @cashier.update(status: cashier_params["false"])
   if @cashier= Cashier.update(params[:id], status: false) 
      redirect_to cashier_path
    end
  end   
  

  
  private 
    def set_cashier
      @cashier = Cashier.find(params[:id])
    end
    def cashier_params
      params.require(:cashier).permit!
    end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  
  def index
    @products = Product.all
  end
  
  def new
    @product = Product.new
  end
  
  def create
    #product = Product.find(params[:product])
    @product = Product.new(product_params)
    if @product.save
        redirect_to @product
    else
      render :new
    end
  end

  def show
    
  end
  
  def update
    if @product.update(product_params)
      redirect_to @product
    end
  end
  
  def edit
  end
  
  def destroy
    if @product = Product.update(params[:id], product_status: false)
      redirect_to products_path
    end
  end
  
  private
    def set_product
      @product = Product.find(params[:id])
    end
    def product_params
      params.require(:product).permit!
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cashiers_helper.rb
module CashiersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admins/index.html.erb
<!--<head>
    <style>
        body{
            background-image: url("https://68.media.tumblr.com/e3a383bd37db7fe709ca9fccbaaf8457/tumblr_osvp3cLJhx1wqqrfao1_1280.png");
            background-attachment:fixed;
            background-repeat:no-repeat;
            background-color:#dc9f36;
        }
    </style>
</head>-->
<body>
<center>
<br>
<Br>
<br>
<br>
<br>
<br>
<br>
<h1>Welcome Admin.</h1>
<p>It is currently <%= DateTime.now.in_time_zone("Singapore").strftime("%B %d %Y") %> and the time is <%= DateTime.now.in_time_zone("Singapore").strftime("%I:%M %p")%>.</p>
<p>What would you like to do?</p>

<div>
     <% if cashier_signed_in? && admin_signed_in?%>
     <%= link_to raw("<i class= 'glyphicon glyphicon-shopping-cart'>" "</i> Show Products"), products_path, class:"btn btn-primary" %>
     <% else %>
    <%= link_to raw("<i class= 'glyphicon glyphicon-shopping-cart'>" "</i> Show Products"), products_path, class:"btn btn-primary" %>
    <%= link_to raw("<i class= 'glyphicon glyphicon-user'>" "</i> Show Cashiers"), cashiers_path, class:"btn btn-primary" %> <br><br><br>
     <%= link_to raw("<i class= 'glyphicon glyphicon-user'>" "</i> Cashier Login"), cashier_session_path, class:"btn btn-success" %>
     <% end %>
</div>
</center>
</body>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in here", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up here", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/cashiers/_cashiers.html.erb
<!--<table class="table table-bordered">
    <thead>
        <tr>
            <th> CASHIERS </th>
            <th> ADMIN ID </th>
            <th> STATUS </th>
            <th colspan="3" class="text-center"> ACTIONS </th>
        </tr>
    </thead>
    <tbody>
        <% @cashiers.each do |cashier| %>
            <tr>
                <td> <%= cashier.name %> </td>
                <td> <%= cashier.status %> </td>
                <td> <%= cashier.admin_id %> </td>
                    <td class="text-center"> <%= link_to 'Show', cashier, class:"btn btn-primary" %> </td>
                    <td class="text-center"> <%= link_to 'Edit', edit_cashier_path(cashier), class:"btn btn-success" %> </td>
                    <td class="text-center"> <%= link_to 'Delete', cashier, method: :delete, class:"btn btn-danger", data: { confirm: 'Are you sure?' }  %> </td>
            </tr>
        <% end %>
        
    </tbody>
</table>

<%= link_to raw("<i class='glyphicon glyphicon-plus'></i> New Cashier"), new_cashier_path, class:"btn btn-primary" %>-->

app/views/cashiers/_form.html.erb
<div class="form-inputs col-md-offset-3 col-md-6">
    <%= simple_form_for(@cashier, url: @cashier.new_record? ? cashiers_path : cashier_path(@cashier), html: { class: 'form-horizontal' }) do |f| %>
    <%= f.input :name %>
    <%= f.input :email, label: 'E-mail' %>
    <center><%= f.input :status, label: 'Activate'%></center>
     <%= link_to raw("<i class= 'glyphicon glyphicon glyphicon-chevron-left'>" "</i> Back"), cashiers_path, class:"btn btn-danger" %>
    <%= f.button :submit, class:"btn btn-success" %>
   
  <% end %>
</div>

app/views/cashiers/cashier_index.html.erb
<p>hi cashier</p>

app/views/cashiers/edit.html.erb
<div class="row">
    <div class="col-md-offset-3 col-md-6">
        <center><h1> EDIT CASHIER </h1></center>
        
        <%= render 'form', cashier: @cashier %>
    </div>
</div>
</center>

app/views/cashiers/index.html.erb
<h3><center>CASHIERS</center></h3>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>CASHIER</th>
            <th>CASHIER'S EMAIL</th>
            <th>STATUS</th>
            <th>SHOW</th>
            <th>EDIT</th>
            <th> DEACTIVATE</th>
        </tr>
    </thead>
    <tbody>
        <% @cashiers.each do |cashier| %>
            <tr>
                <td> <%= cashier.name %> </td>
                <td> <%= cashier.email %> </td>
                <!--<td> <%= cashier.status %> </td>-->
                <% if cashier.status == true %>
                    <td class="text-center"> Active </td>
                <% else %>
                    <td class="text-center"> Deactivated </td>
                <% end %>
                <td class="text-center"> <%= link_to 'Review', cashier, class:"btn btn-info" %> </td>
                <td class="text-center"> <%= link_to 'Edit', edit_cashier_path(cashier), class:"btn btn-primary" %> </td>
                <td class="text-center"> <%= link_to 'Deactivate', cashier, method: :delete, class:"btn btn-danger", data: { confirm: 'Deactivating: Are You Sure?' }  %> </td>
            </tr>
        <% end %>
        
    </tbody>
</table>

<%= link_to raw("<i class= 'glyphicon glyphicon-user'>" "</i>  Add New Cashiers"), new_cashier_path, class:"btn btn-primary" %>
<%= link_to raw("<i class= 'glyphicon glyphicon-repeat'>" "</i> Return to Admin Page"), admins_path, class:"btn btn-danger" %>

app/views/cashiers/new.html.erb
<center>
<div class="row">
    <div class="col-md-offset-3 col-md-6">
        <h1> ADD A NEW CASHIER </h1>
        
        <%= render 'form', cashier: @cashier %>
    </div>
</div>
</center>

app/views/cashiers/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/cashiers/show.html.erb
<div class="col-md-9">
    <div class="row">
        <h3>Show Cashier</h3>
         <table class="table table-bordered">
            <thead>
                <tr>
                    <td> <strong> CASHIER NAME: </strong> </td>
                    <td> <strong> ID: </strong></td>
                    <td> <strong> CASHIER STATUS: </strong></td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td> <%= @cashier.name %> </td>
                    <td> <%= current_admin.id %></td>
                    <td> <%= @cashier.status %> </td>
               
                    <div class="pull-right">
                        <%= link_to 'Back', cashiers_path, class:"btn btn-danger" %>
                        <%= link_to raw("<i class= 'glyphicon glyphicon-user'>" "</i> cashier login"), cashier_session_path, class:"btn btn-info" %>
                        
                    </div>
                </tr>
            </tbody>
    </div>
</div>

app/views/cashiers/show_cashiers.html.erb
<div class="col-md-9">
    <div class="row">
        <h3>Show Cashier</h3>
         <table class="table table-bordered">
            <thead>
                <tr>
                    <td> <strong> CASHIER NAME: </strong> </td>
                    <td> <strong> CASHIER PASSWORD: </strong></td>
                    <td> <strong> CASHIER STATUS: </strong></td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td> <%= @cashier.cashier_name %></td>
                    <td> $<%= @cashier.cashier_status %> </td>
                    <td> <%= @cashier.status %> </td>
                    <div class="pull-right">
                        <%= link_to 'Back to Products Page', cashiers_path, class:"btn btn-danger" %>
                        
                    </div>
                </tr>
            </tbody>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>A S V U S POS SYSTEM</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">A S V U S</a>
        </div>
        <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
        <li>
          <% if admin_signed_in? %>
          <li><%= link_to "Products", products_path %></li> 
          <li><%= link_to "Cashiers", cashiers_path %></li>
          <% end %>
          <!--destroy session path to admin if v-->
          <% if cashier_signed_in? %>
          <li><%= link_to "Orders dapat dito pero in the mean time just a random page", cashiers_path %></li>
     
          <% end %>
        </li>
        </ul>

          <p class="navbar-text pull-right">
          <% if admin_signed_in? %>
            Logged in as <strong><%= current_admin.email %></strong>.
            <%= link_to 'Edit profile', edit_admin_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link'  %>
            
          <% end %>
          <% if cashier_signed_in? %>
            <%= link_to 'Edit profile', edit_cashier_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_cashier_session_path, method: :delete, :class => 'navbar-link'  %>
            
          <% end %>
          </p>
        </div>
      </div>
    </nav> 
    
    <div class="container">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<div class="form-inputs col-md-offset-3 col-md-6">
  <%= simple_form_for(@product, html: { class: 'form-horizontal' }) do |f| %>
    <%= f.input :product_name %>
    <%= f.input :product_price %>
    <center><%= f.input :product_status, label: 'Activate'  %></center>
     <%= link_to raw("<i class= 'glyphicon glyphicon glyphicon-chevron-left'>" "</i> Back"), products_path, class:"btn btn-danger" %>
    <%= f.button :submit, class:"btn btn-success" %>
   
  <% end %>
</div>

app/views/products/create_products.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/edit.html.erb
<div class="row">
    <div class="col-md-offset-3 col-md-6">
        <center><h1> EDIT PRODUCT </h1></center>
        
        <%= render 'form', product: @product %>
    </div>
</div>
</center>

app/views/products/index.html.erb
<center><h3>PRODUCTS</h3></center>
<table class="table table-bordered">
    <thead>
        <tr>
            <th class="text-center col-md-3">PRODUCT NAME </th>
            <th class="text-center col-md-3">PRODUCT PRICE</th>
            <th class="text-center col-md-2">STATUS</th>
            <th colspan="4" class="text-center">ACTIONS</th>
            
        </tr>
    </thead>
    <tbody>
        <% @products.each do |products| %>
            <tr>
                <td> <%= products.product_name %> </td>
                <td> $<%= products.product_price %> </td>
                <% if products.product_status == true %>
                    <td class="text-center"> Active </td>
                <% else %>
                    <td class="text-center"> Deactivated </td>
                <% end %>
                <td class="text-center"> <%= link_to 'Review', products, class:"btn btn-info" %> </td>
                <td class="text-center"> <%= link_to 'Edit', edit_product_path(products), class:"btn btn-primary" %> </td>
                <td class="text-center"> <%= link_to 'Deactivate', products, method: :delete, class:"btn btn-danger", data: { confirm: 'Removing Product: Are You Sure?' }  %> </td>
            </tr> 
        <% end %>
        
    </tbody>
</table>
    <%= link_to raw("<i class= 'glyphicon glyphicon-shopping-cart'>" "</i> Add New Product"), new_product_path, class:"btn btn-success" %>
    <%= link_to raw("<i class= 'glyphicon glyphicon-repeat'>" "</i> Return to Admin Page"), admins_path, class:"btn btn-danger" %>

app/views/products/new.html.erb
<center>
<div class="row">
    <div class="col-md-offset-3 col-md-6">
        <h1> ADD A NEW PRODUCT </h1>
        
        <%= render 'form', product: @product %>
    </div>
</div>
</center>

app/views/products/show.html.erb
<div class="col-md-9">
    <div class="row">
        <h3>Show Product</h3>
         <table class="table table-bordered">
            <thead>
                <tr>
                    <td> <strong> PRODUCT NAME: </strong> </td>
                    <td> <strong> PRODUCT PRICE: </strong></td>
                    <td> <strong> PRODUCT STATUS: </strong></td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td> <%= @product.product_name %> </td>
                    <td> $<%= @product.product_price %> </td>
                    <td> <%= @product.product_status %> </td>
                    
                    <div class="pull-right">
                        <%= link_to 'Back to Products Page', products_path, class:"btn btn-danger" %>
                    </div>
                </tr>
            </tbody>
    </div>
</div>

app/views/products/show_products.html.erb
<div class="col-md-9">
    <div class="row">
        <h3>Show Product</h3>
         <table class="table table-bordered">
            <thead>
                <tr>
                    <td> <strong> PRODUCT NAME: </strong> </td>
                    <td> <strong> PRODUCT PRICE: </strong></td>
                    <td> <strong> PRODUCT STATUS: </strong></td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td> <%= @product.product_name %> </td>
                    <td> $<%= @product.product_price %> </td>
                    <td> <%= @product.product_status %> </td>
                    <div class="pull-right">
                        <%= link_to 'Back to Products Page', products_path, class:"btn btn-danger" %>
                    </div>
                </tr>
            </tbody>
    </div>
</div>